version: "3.5"

services:
  flights:
    container_name: flights
    environment:
        - TZ=Europe/Berlin
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./apidata:/app/apidata:rw
    restart: always
