services:
  flights:
    image: hanjohansen/flights:latest
    container_name: flights
    environment:
        - TZ=Europe/Berlin
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./apidata:/app/apidata:rw
      - ./storage:/app/wwwroot/Storage:rw
    restart: always
