version: "3.5"

services:
  flights:
    container_name: flights
    environment:
        - TZ=Europe/Berlin
    build: 
      context: .
      dockerfile: dockerfile.local
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./apidata:/app/apidata:rw
      - ./storage:/app/wwwroot/Storage:rw
    restart: always
