using Flights.Domain.Entities;
using Flights.Domain.Entities.Game;

namespace Flights.Domain.State.Checkout;
public class CheckoutRepository
{
    private readonly Dictionary<int, DartsState> _checkouts;

    public CheckoutRepository(){
        _checkouts = CreateCheckouts();
    }

    public DartsState? GetCheckout(int score, int remDarts){
        if(!_checkouts.ContainsKey(score))
            return null;
        
        var checkout = _checkouts[score];
        if(remDarts >= checkout.GetDartsList().Count)
            return checkout;

        return null;
    }

    private Dictionary<int, DartsState> CreateCheckouts(){
        return new Dictionary<int, DartsState>
        {
            {170, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 25, 0))},
            {167, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 25, 0))},
            {164, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 25, 0))},
            {161, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 25, 0))},
            {160, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 20, 0))},
            {158, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 19, 0))},
            {157, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 20, 0))},
            {156, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 18, 0))},
            {155, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 19, 0))},
            {154, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 20, 0))},
            {153, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 18, 0))},
            {152, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 16, 0))},
            {151, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 20, 0))},
            {150, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 18, 0))},
            {149, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 16, 0))},
            {148, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 20, 0))},
            {147, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 18, 0))},
            {146, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 16, 0))},
            {145, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 14, 0))},
            {144, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 12, 0))},
            {143, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 16, 0))},
            {142, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 14, 0))},
            {141, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 12, 0))},
            {140, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 10, 0))},
            {139, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 14, 0), new DartState(DartModifier.Double, 20, 0))},
            {138, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 12, 0))},
            {137, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 15, 0), new DartState(DartModifier.Double, 16, 0))},
            {136, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 8, 0))},
            {135, new DartsState(new DartState(DartModifier.None, 25, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 25, 0))},
            {134, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 14, 0), new DartState(DartModifier.Double, 16, 0))},
            {133, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 11, 0), new DartState(DartModifier.Double, 20, 0))},
            {132, new DartsState(new DartState(DartModifier.Double, 25, 0), new DartState(DartModifier.Triple, 14, 0), new DartState(DartModifier.Double, 20, 0))},
            {131, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 13, 0), new DartState(DartModifier.Double, 16, 0))},
            {130, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 5, 0))},
            {129, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 12, 0))},
            {128, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Triple, 14, 0), new DartState(DartModifier.Double, 16, 0))},
            {127, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 8, 0))},
            {126, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 6, 0))},
            {125, new DartsState(new DartState(DartModifier.Double, 25, 0), new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 12, 0))},
            {124, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 8, 0))},
            {123, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 9, 0))},
            {122, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 7, 0))},
            {121, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Triple, 11, 0), new DartState(DartModifier.Double, 14, 0))},
            {120, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 20, 0), new DartState(DartModifier.Double, 20, 0))},
            {119, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Triple, 12, 0), new DartState(DartModifier.Double, 13, 0))},
            {118, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 18, 0), new DartState(DartModifier.Double, 20, 0))},
            {117, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 17, 0), new DartState(DartModifier.Double, 20, 0))},
            {116, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 16, 0), new DartState(DartModifier.Double, 20, 0))},
            {115, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 15, 0), new DartState(DartModifier.Double, 20, 0))},
            {114, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 14, 0), new DartState(DartModifier.Double, 20, 0))},
            {113, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.None, 16, 0), new DartState(DartModifier.Double, 20, 0))},
            {112, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 12, 0), new DartState(DartModifier.Double, 20, 0))},
            {111, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 11, 0), new DartState(DartModifier.Double, 20, 0))},
            {110, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 10, 0), new DartState(DartModifier.Double, 20, 0))},
            {109, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 9, 0), new DartState(DartModifier.Double, 20, 0))},
            {108, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 16, 0), new DartState(DartModifier.Double, 16, 0))},
            {107, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.None, 18, 0), new DartState(DartModifier.Double, 16, 0))},
            {106, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 14, 0), new DartState(DartModifier.Double, 16, 0))},
            {105, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 13, 0), new DartState(DartModifier.Double, 16, 0))},
            {104, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.None, 18, 0), new DartState(DartModifier.Double, 16, 0))},
            {103, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.None, 14, 0), new DartState(DartModifier.Double, 16, 0))},
            {102, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 10, 0), new DartState(DartModifier.Double, 16, 0))},
            {101, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.None, 9, 0), new DartState(DartModifier.Double, 16, 0))},
            {100, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {99, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.None, 10, 0), new DartState(DartModifier.Double, 16, 0))},
            {98, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 19, 0), null)},
            {97, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {96, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 18, 0), null)},
            {95, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 19, 0), null)},
            {94, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {93, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 18, 0), null)},
            {92, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {91, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {90, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 15, 0), null)},
            {89, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {88, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 14, 0), null)},
            {87, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 18, 0), null)},
            {86, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {85, new DartsState(new DartState(DartModifier.Triple, 15, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {84, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {83, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {82, new DartsState(new DartState(DartModifier.Double, 25, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {81, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {80, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 10, 0), null)},
            {79, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 11, 0), null)},
            {78, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {77, new DartsState(new DartState(DartModifier.Triple, 19, 0), new DartState(DartModifier.Double, 10, 0), null)},
            {76, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {75, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {74, new DartsState(new DartState(DartModifier.Triple, 14, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {73, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 11, 0), null)},
            {72, new DartsState(new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {71, new DartsState(new DartState(DartModifier.Triple, 13, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {70, new DartsState(new DartState(DartModifier.Triple, 18, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {69, new DartsState(new DartState(DartModifier.Triple, 15, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {68, new DartsState(new DartState(DartModifier.Triple, 20, 0), new DartState(DartModifier.Double, 4, 0), null)},
            {67, new DartsState(new DartState(DartModifier.Triple, 17, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {66, new DartsState(new DartState(DartModifier.Triple, 10, 0), new DartState(DartModifier.Double, 18, 0), null)},
            {65, new DartsState(new DartState(DartModifier.Triple, 11, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {64, new DartsState(new DartState(DartModifier.Triple, 16, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {63, new DartsState(new DartState(DartModifier.Triple, 13, 0), new DartState(DartModifier.Double, 12, 0), null)},
            {62, new DartsState(new DartState(DartModifier.Triple, 10, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {61, new DartsState(new DartState(DartModifier.Triple, 15, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {60, new DartsState(new DartState(DartModifier.None, 20, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {59, new DartsState(new DartState(DartModifier.None, 19, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {58, new DartsState(new DartState(DartModifier.None, 18, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {57, new DartsState(new DartState(DartModifier.None, 17, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {56, new DartsState(new DartState(DartModifier.None, 16, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {55, new DartsState(new DartState(DartModifier.None, 15, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {54, new DartsState(new DartState(DartModifier.None, 14, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {53, new DartsState(new DartState(DartModifier.None, 13, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {52, new DartsState(new DartState(DartModifier.None, 12, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {51, new DartsState(new DartState(DartModifier.None, 19, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {50, new DartsState(new DartState(DartModifier.None, 18, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {49, new DartsState(new DartState(DartModifier.None, 9, 0), new DartState(DartModifier.Double, 20, 0), null)},
            {48, new DartsState(new DartState(DartModifier.None, 16, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {47, new DartsState(new DartState(DartModifier.None, 15, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {46, new DartsState(new DartState(DartModifier.None, 14, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {45, new DartsState(new DartState(DartModifier.None, 13, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {44, new DartsState(new DartState(DartModifier.None, 12, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {43, new DartsState(new DartState(DartModifier.None, 11, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {42, new DartsState(new DartState(DartModifier.None, 10, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {41, new DartsState(new DartState(DartModifier.None, 9, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {40, new DartsState(new DartState(DartModifier.Double, 20, 0), null, null)},
            {39, new DartsState(new DartState(DartModifier.None, 7, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {38, new DartsState(new DartState(DartModifier.Double, 19, 0), null, null)},
            {37, new DartsState(new DartState(DartModifier.None, 5, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {36, new DartsState(new DartState(DartModifier.Double, 18, 0), null, null)},
            {35, new DartsState(new DartState(DartModifier.None, 3, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {34, new DartsState(new DartState(DartModifier.Double, 17, 0), null, null)},
            {33, new DartsState(new DartState(DartModifier.None, 1, 0), new DartState(DartModifier.Double, 16, 0), null)},
            {32, new DartsState(new DartState(DartModifier.Double, 16, 0), null, null)},
            {31, new DartsState(new DartState(DartModifier.None, 15, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {30, new DartsState(new DartState(DartModifier.Double, 15, 0), null, null)},
            {29, new DartsState(new DartState(DartModifier.None, 13, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {28, new DartsState(new DartState(DartModifier.Double, 14, 0), null, null)},
            {27, new DartsState(new DartState(DartModifier.None, 11, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {26, new DartsState(new DartState(DartModifier.Double, 13, 0), null, null)},
            {25, new DartsState(new DartState(DartModifier.None, 9, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {24, new DartsState(new DartState(DartModifier.Double, 12, 0), null, null)},
            {23, new DartsState(new DartState(DartModifier.None, 7, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {22, new DartsState(new DartState(DartModifier.Double, 11, 0), null, null)},
            {21, new DartsState(new DartState(DartModifier.None, 5, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {20, new DartsState(new DartState(DartModifier.Double, 10, 0), null, null)},
            {19, new DartsState(new DartState(DartModifier.None, 3, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {18, new DartsState(new DartState(DartModifier.Double, 9, 0), null, null)},
            {17, new DartsState(new DartState(DartModifier.None, 1, 0), new DartState(DartModifier.Double, 8, 0), null)},
            {16, new DartsState(new DartState(DartModifier.Double, 8, 0), null, null)},
            {15, new DartsState(new DartState(DartModifier.None, 7, 0), new DartState(DartModifier.Double, 4, 0), null)},
            {14, new DartsState(new DartState(DartModifier.Double, 7, 0), null, null)},
            {13, new DartsState(new DartState(DartModifier.None, 5, 0), new DartState(DartModifier.Double, 4, 0), null)},
            {12, new DartsState(new DartState(DartModifier.Double, 6, 0), null, null)},
            {11, new DartsState(new DartState(DartModifier.None, 3, 0), new DartState(DartModifier.Double, 4, 0), null)},
            {10, new DartsState(new DartState(DartModifier.Double, 5, 0), null, null)},
            {9, new DartsState(new DartState(DartModifier.None, 1, 0), new DartState(DartModifier.Double, 4, 0), null)},
            {8, new DartsState(new DartState(DartModifier.Double, 4, 0), null, null)},
            {7, new DartsState(new DartState(DartModifier.None, 3, 0), new DartState(DartModifier.Double, 2, 0), null)},
            {6, new DartsState(new DartState(DartModifier.Double, 3, 0), null, null)},
            {5, new DartsState(new DartState(DartModifier.None, 1, 0), new DartState(DartModifier.Double, 2, 0), null)},
            {4, new DartsState(new DartState(DartModifier.Double, 2, 0), null, null)},
            {3, new DartsState(new DartState(DartModifier.None, 1, 0), new DartState(DartModifier.Double, 1, 0), null)},
            {2, new DartsState(new DartState(DartModifier.Double, 1, 0), null, null)}
        };
    }
}